import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

// Clerk
import { ClerkProvider } from "@clerk/nextjs";
// Radix UI
import "@radix-ui/themes/styles.css";
import { Theme, ThemePanel } from "@radix-ui/themes";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<ClerkProvider>
			<html lang="en" suppressHydrationWarning>
				<body className={inter.className}>
					<Theme
						appearance="dark"
						accentColor="orange"
						grayColor="slate"
						radius="small"
					>
						{children}
						<ThemePanel />
					</Theme>
				</body>
			</html>
		</ClerkProvider>
	);
}
