"use client";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
// Redux
import { Provider } from "react-redux";
import store from "@/app/store";
// Clerk
import { ClerkProvider } from "@clerk/nextjs";
import { dark } from "@clerk/themes";
import { enUS, trTR } from "@clerk/localizations";
// Radix UI
import "@radix-ui/themes/styles.css";
import { Theme, ThemePanel } from "@radix-ui/themes";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
// 	title: "Portfolio",
// 	description: "Generated by create blakfy app",
// };

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" suppressHydrationWarning>
			<body className={inter.className}>
				<Provider store={store}>
					<ClerkProvider localization={enUS}>
						<Theme
							appearance="light"
							accentColor="orange"
							grayColor="slate"
							radius="small"
						>
							{children}
						</Theme>
					</ClerkProvider>
				</Provider>
			</body>
		</html>
	);
}
