// next
import type { Metadata } from "next";
// Components
import Navbar from "@/app/Components/Navbar/Navbar";
// ------------------------------

export const metadata: Metadata = {
	title: "Heello :)",
	description: "Generated by create blakfy app",
};

export default function Home() {
	return (
		<>
			<Navbar />
			<div className="flex h-screen justify-center items-center">
				<h1 className="text-3xl">
					Home Page{metadata.title?.toString() || "Başlik Yok"}
				</h1>
				<p>Metin ingilizce</p>
			</div>
		</>
	);
}
