import type { Metadata } from "next";
import { SignIn } from "@clerk/nextjs";

export const metadata: Metadata = {
	title: "Sign In",
	description: "Generated by create blakfy app",
};

export default function Page() {
	return (
		<SignIn
			routing="path" // Sayfalarınız için kullanılan yönlendirme stratejisini belirler. 'hash', 'path' veya 'virtual' olabilir. Next.js veya Remix için ortam değişkenleri kullanılıyorsa, bu değer 'path' olarak ayarlanır.
			path="/sign-in" // Path tabanlı yönlendirme kullanıldığında bileşenin monte edildiği yolunu belirtir, örneğin /sign-in.
			redirectUrl="/" // Başarılı bir şekilde giriş yapılması veya kayıt olunması durumunda yönlendirilecek tam URL veya yolunu belirler.
			signUpUrl="/sign-up/" // Kayıt Ol' bağlantısının hedefini belirlemek için kullanılır, tam URL veya yol olarak sağlanır.
			afterSignInUrl="/" // Başarılı bir şekilde giriş yapılması durumunda yönlendirilecek tam URL veya yolunu belirler.
			afterSignUpUrl="/" // Başarılı bir şekilde kayıt olunması durumunda yönlendirilecek tam URL veya yolunu belirler.
		/>
	);
}
