import type { Metadata } from "next";
import { SignUp } from "@clerk/nextjs";
import Navbar from "@/app/Components/Navbar/Navbar";

export const metadata: Metadata = {
	title: "Sign Up",
	description: "Generated by create blakfy app",
};

export default function Page() {
	return (
		<>
			<Navbar />
			<div className="flex h-screen justify-center items-center flex-col gap-10">
				<SignUp signInUrl="/sign-in" />
			</div>
		</>
	);
}
